apiVersion: v1
kind: Secret
metadata:
  name: mt-secrets
type: Opaque   #Tipo padrão (chave-valor simples)
stringData:
  POSTGRES_DB: "nome_banco"
  username: "usuario_banco"  #CNPG exige que o usuário seja chamado "username"
  password: "senha_banco"   #CNPG exige que a senha seja chamada "password"
  APP_SECRET_KEY: "secret_key"
  DJANGO_SUPERUSER_PASSWORD: "senha_superuser"
  EMAIL_HOST_PASSWORD: "senha_email"